config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: "home#index"
  get '/ranking' => 'home#ranking'
  
  resources :teams
  resources :matches do
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
	has_and_belongs_to_many :teams

		scope :winning_team, -> { where('team_one_score || team_two_score == 10') }

		attr_accessor :assign_winner, :team_wins

  	def winner?
			return team_one if team_one_score == 10
			return team_two if team_two_score == 10
			nil
		end

		def assign_winner
			self.update(winning_team: winner?)
		end

		def team_wins
			# team = Team.find(winning_team.to_s)
			# Team.update(winning_team.to_s, wins: "1")
			Team.increment_counter(:wins, winning_team.to_s)
			# add_one to team
		end

		def team_win_percentage
			# team = Team.find(winning_team.to_s)
			# Team.update(winning_team.to_s, wins: "1")
			# add_one to team
		end

		# def tally_wins
		# 	count = 0
		# 	@team = Team.all
		# 	@team.each do |team|
		# 		if winning_team == team.id
		# 			count += 1
		# 		end
		# 	end
		# end

		  # def win_counter
  # 	count = 0
  # 	if match.winning_team == team.id
  # 	 count += 1
  # 	end
  # end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
	belongs_to :team
	belongs_to :user
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_many :users, through: :participants
  has_many :participants
  has_and_belongs_to_many :matches

  # def wins
  # 	@matches = Match.all
  # 	@matches.each do |match|
  # 		return "tesing 123" if match.winner? == team.id
  # 	end
  # end 

  # Match.where('(winning_team == team.id)').count

  # def win_counter
  # 	count = 0
  # 	if match.winning_team == team.id
  # 	 count += 1
  # 	end
  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :teams, through: :participants
  has_many :participants

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@matches = Match.all.order(id: :desc).limit(10)
	end

	def ranking
		@teams = Team.all
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
	
  def new
		@match = Match.new
		# @users = User.all
    # 2.times { @match.teams.build }
    # @team = Team.new
	end

	def create
    @match = Match.new(match_params)
    @match.teams << Team.find(params[:match][:team_one])
    @match.teams << Team.find(params[:match][:team_two])
    @match.assign_winner
    @match.team_wins
    # @match.teams << Team.find(params[:match][:winning_team])
    # p "TEAM ONE SCORE:"
    # p params[:match][:team_one_score]
    # @match.teams.first. << Team.find(params[:match][:team_one_score])
    # @match.teams. << Team.find(params[:match][:team_two_score])
    if @match.save
    	flash[:notice] = 'Match created successfully'
    	redirect_to '/'
    else
    	render 'new'
    end
	end

	def show
    @match = Match.find(params[:id])
	end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      flash[:notice] = 'Match updated successfully'
      redirect_to '/'
    else
      flash[:alert] = "Profile could not be updated"
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    if @match.destroy
      flash[:notice] = 'Match deleted successfully'
      redirect_to '/'
    else
      flash[:alert] = 'Sorry something went wrong. Your match was not deleted.'
      redirect_to '/'
    end
  end

  def match_params
    params.require(:match).permit(:match_name, :team_one,
    															:team_two, :best_of, 
                                  :team_one_score, :team_two_score, :winning_team)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController

	def index
		@teams = Team.all
	end

	def new
		@team = Team.new
		@users = User.all
	end

	def create
    @team = Team.new(team_params)
    if @team.save
    	flash[:notice] = 'Team created successfully'
    	redirect_to teams_path
    else
    	render 'new'
    end
	end

	def show
		@team = Team.find(params[:id])
	end

	# def destroy
 #    @team = Team.find(params[:id])
 #    if @team.destroy
 #      flash[:notice] = 'Team deleted successfully'
 #      redirect_to '/'
 #    else
 #      flash[:alert] = 'Sorry something went wrong. Your team was not deleted.'
 #      redirect_to '/'
 #    end
 #  end

	def team_params
    params.require(:team).permit(:player_one, :player_two)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<section class="index">
	<% if current_user %>
		<div class="col-sm-6 col-centered">
		</div>

<div class="container">          
  <table class="table">
  <h2 class="text-center">Here are the most recent matchups</h2>
    <thead>
      <tr>
        <th>Matchup</th>
        <th>Date</th>
        <th>Score</th>
        <th>Winner</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <%  %>
	      <tr>
	      <% @matches.each do |match| %>
	        <td>
	        <%= link_to "Team #1", team_path(match.teams.first) %>
					<%= match.teams.first.player_one %> & 
					<% if match.teams.first.player_two %> 
						<%= match.teams.first.player_two %> 
					<% end %>

					vs.
					
					<%= link_to "Team #2", team_path(match.teams.last) %>
					<%= match.teams.last.player_one %> & 
					<% if match.teams.last.player_two %> 
						<%= match.teams.last.player_two %> 
					<% end %>
					</td>
			    <td><%= match.created_at.strftime("%m/%d/%Y")  %></td>
			    <td><%= match.team_one_score %> : <%= match.team_two_score %></td>
			    <td><% if match.winner? == match.team_one %> <%= "Team 1" %> <% else %> <%= "Team 2" %> <% end %></td>
			    <td><%= link_to "Edit Match", edit_match_path(match) %> / <%= link_to "Delete Match", match_path(match), method: :delete %></td>
			  </tr>
			<% end %>
    </tbody>
  </table>
</div>


	<% else %>
		<div class="md-col-6">
			<div class="jumbotron absolute">
			  <h2 class="text-center">We keep track of your awesome foosball skills :)</h2>
			  <div class="centered">
    			<%= link_to "Join today!", new_user_registration_path, role: "button", class: "btn btn-larg btn-primary" %>
				</div>
			</div>
	<% end %>
</section>

app/views/home/ranking.html.erb
	<div class="container">
		<% if @teams.any? %>
	 		<h2 class="text-center">Here are all the teams that have played together</h2> 
		  <table class="table">
		    <thead>
		      <tr>
		        <th>Player One</th>
		        <th>Player Two</th>
		        <th>Win Percentage</th>
		        <th>Total Wins</th>
		        <th>Options</th>
		      </tr>
		    </thead>
		    <tbody>
		      <% @teams.each do |team| %>
			      <tr>

			        <td><%= team.player_one %></td>
			        <td><%= team.player_two %></td>
			        <td><%= ((team.wins.to_f / team.matches.count) * 100).round(2) %> </td>
			        <td><%= team.wins %></td>
			        <td><%= link_to "View Team", team_path(team), class: "" %>
			         / <%= link_to "Delete Team", team_path(team), method: :delete %></td>
			      </tr>
		     	<% end %>
		    </tbody>
		  </table>
		<% else %>
			<p>No teams yet.<p>
		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fantasy Foosball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Arvo:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><h1>Fantasy Foosball</h1>
        </a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "View ranking", ranking_path, class: "" %> </li>
            <li><%= link_to "All Teams", teams_path, class: "" %> </li>
            <li><%= link_to "Create new team", new_team_path, class: "" %></li>
            <li><%= link_to "Create new match", new_match_path, class: "" %> </li> 
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "" %> </li>
            <% else %>
            <li><%= link_to "Sign in", new_user_session_path, class: "" %> </li>
            <li><%= link_to "Sign up", new_user_registration_path, class: "" %> </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> data-dismissable", role="alert" >
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  <%= yield %>

  <section class="space-20"> </div>
  
  </div>
</body>
</html>

app/views/matches/edit.html.erb
<div class="col-sm-6 col-centered">
  <h2 class="text-center">Edit your new matchup below</h2>
	<%= form_for [@match], :html => {:multipart => true} do |f| %>
		<%= f.text_field :match_name, placeholder: "Enter Matchup Name (e.g. The Royal Rumble", class: "form-control" %>
		<%= f.select :team_one, User.all.map(&:first_name), class: "form-control" %>
		<%= f.select :team_two, User.all.map(&:first_name), class: "form-control" %>
	  <%= f.submit "Update Match!", class: "form-control btn btn-primary" %>
	<% end %>
</div>

app/views/matches/new.html.erb
<div class="col-sm-6 col-centered">
  <h2 class="text-center">Create your new matchup below</h2>
	<%= form_for [@match], :html => {:multipart => true} do |f| %>
		<%= f.label :team_one %>
		<%= f.select :team_one, Team.all.collect {|team| ["#{team.player_one}" + " & " "#{team.player_two}", team.id] }, class: "form-control" %>
		<%= f.select :team_one_score, (0..10), class: "form-control" %>
		<br>
		<%= f.label :team_two %>
		<%= f.select :team_two, Team.all.collect {|team| ["#{team.player_one}" + " & " "#{team.player_two}", team.id] }, class: "form-control" %>
		<%= f.select :team_two_score, (0..10), class: "form-control" %>
		<br>
	  <%= f.submit "Create Match!", class: "form-control btn btn-primary" %>
	<% end %>
</div>

app/views/matches/show.html.erb
<div class="container">          
  <table class="table">
    <thead>
      <tr>
        <th>Matchup</th>
        <th>Date</th>
        <th>Score</th>
        <th>Winner</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <%  %>
	      <tr>
	        <td>
	        <%= link_to "Team #1", team_path(@match.teams.first) %>
					<%= @match.teams.first.player_one %> & 
					<% if @match.teams.first.player_two %> 
						<%= @match.teams.first.player_two %> 
					<% end %>

					vs.
					
					<%= link_to "Team #2", team_path(@match.teams.last) %>
					<%= @match.teams.last.player_one %> & 
					<% if @match.teams.last.player_two %> 
						<%= @match.teams.last.player_two %> 
					<% end %>
					</td>
			    <td><%= @match.created_at.strftime("%m/%d/%Y")  %></td>
			    <td><%= @match.team_one_score %> : <%= @match.team_two_score %></td>
			    <td> <% if @match.winner? == @match.team_one %> <%= "Team 1" %> <% else %> <%= "Team 2" %> <% end %></td>
			    <td><%= link_to "Edit Match", edit_match_path(@match) %> / <%= link_to "Delete Match", match_path(@match), method: :delete %></td>
			  </tr>
    </tbody>
  </table>
</div>